# Generated by Django 4.1.1 on 2022-09-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=1234, unique=True),
            preserve_default=False,
        ),
    ]
