# Generated by Django 4.1.1 on 2022-11-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
