# Generated by Django 4.1.1 on 2022-11-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0002_remove_customer_first_name_remove_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('local', 'Local'), ('external', 'External'), ('loan', 'Loan'), ('operational', 'Operational')], default='local', max_length=15),
        ),
    ]
