# Generated by Django 4.1.1 on 2022-09-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0002_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='is_creditor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('private', 'Private'), ('business', 'Business'), ('loan', 'Loan'), ('bank', 'Bank')], default='private', max_length=10),
        ),
    ]
