# Generated by Django 4.1.1 on 2022-10-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0003_ledger_is_creditor_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
