# Generated by Django 4.1.1 on 2022-11-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0003_alter_account_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('api_url', models.CharField(max_length=50)),
                ('bank_type', models.CharField(choices=[('local', 'Local'), ('external', 'External')], default='external', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_customer',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('loan', 'Loan'), ('operational', 'Operational')], default='customer', max_length=15),
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='account_management_app.bank'),
            preserve_default=False,
        ),
    ]
