# Generated by Django 4.1.1 on 2022-12-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0003_account_is_saving_account_ledger_is_saving_account_and_more'),
        ('account_management_app', '0004_bank_remove_account_is_customer_and_more'),
    ]

    operations = [
    ]
