# Generated by Django 4.1.1 on 2022-11-28 20:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0004_bank_remove_account_is_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLedgerMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('local_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_management_app.account')),
                ('target_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_management_app.bank')),
            ],
        ),
    ]
