# Generated by Django 4.1.1 on 2022-12-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0005_externalledgermetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalledgermetadata',
            name='local_account',
        ),
        migrations.RemoveField(
            model_name='externalledgermetadata',
            name='target_bank',
        ),
        migrations.AddField(
            model_name='externalledgermetadata',
            name='receiver_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='account_management_app.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalledgermetadata',
            name='sender_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='account_management_app.account'),
            preserve_default=False,
        ),
    ]
