# Generated by Django 4.1.1 on 2022-12-19 17:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0005_merge_20221219_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLedgerMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sender_account_number', models.IntegerField()),
                ('receiver_account_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('reservation_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_management_app.account')),
            ],
        ),
    ]
