# Generated by Django 4.1.1 on 2022-10-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0005_ledger_transaction_id_alter_ledger_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('private', 'Private'), ('business', 'Business'), ('loan', 'Loan')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
