# Generated by Django 4.1.1 on 2022-12-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0006_externalledgermetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalledgermetadata',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('to_be_confirmed', 'To Be Confirmed'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
