# Generated by Django 4.1.1 on 2022-10-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0006_alter_account_account_type_alter_ledger_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='is_loan',
            field=models.BooleanField(default=False),
        ),
    ]
