# Generated by Django 4.1.1 on 2022-12-19 19:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0007_alter_externalledgermetadata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalledgermetadata',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
