# Generated by Django 4.1.1 on 2023-01-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0004_conversation'),
        ('account_management_app', '0009_alter_externalledgermetadata_status'),
    ]

    operations = [
    ]
