# Generated by Django 4.1.1 on 2023-01-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0010_merge_20230115_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='json_array',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
