# Generated by Django 4.1.1 on 2023-01-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_app', '0011_customer_json_array_delete_conversation'),
        ('account_management_app', '0011_externalledgermetadata_failed_attempts_and_more'),
    ]

    operations = [
    ]
